EcommerceWebsite/Models/CategoryViewModel.cs
using DevClothing.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EcommerceWebsite.Models
{
    public class NewCategoryViewModel
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageURL { get; set; }
        public bool isFeatured { get; set; }
    }
    public class CategorySearchViewModel
    {
        public List<Category> Categories { get; set; }
        public string SearchTerm { get; set; }
    }
    public class EditCategoryViewModel
    {
        public int ID { get; set; }

        public string Name { get; set; }
        public string Description { get; set; }

        public string ImageURL { get; set; }

        public bool isFeatured { get; set; }
    }
}

EcommerceWebsite/Controllers/CategoryController.cs
using DevClothing.Entities;
using DevClothing.Services;
using EcommerceWebsite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EcommerceWebsite.Controllers
{
    public class CategoryController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CategoryTable(string search)
        {
            CategorySearchViewModel model = new CategorySearchViewModel();

            model.Categories = CategoriesService.publicInstance.GetCategories();

            if (!string.IsNullOrEmpty(search))
            {
                model.SearchTerm = search;

                model.Categories = model.Categories.Where(p => p.Name != null && p.Name.ToLower().Contains(search.ToLower())).ToList();
            }

            return PartialView("CategoryTable", model);
        }

        // GET: Category
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(NewCategoryViewModel model)
        {
            var newCategory = new Category();
            newCategory.Name = model.Name;
            newCategory.Description = model.Description;
            newCategory.ImageURL = model.ImageURL;
            newCategory.isFeatured = model.isFeatured;
            CategoriesService.publicInstance.SaveCategory(newCategory);
            return RedirectToAction("CategoryTable");
        }
        [HttpGet]
        public ActionResult Edit(int ID)
        {
            EditCategoryViewModel model = new EditCategoryViewModel();
            var category = CategoriesService.publicInstance.GetCategory(ID);
            model.ID            = category.ID;
            model.Name          = category.Name;
            model.Description   = category.Description;
            model.ImageURL      = category.ImageURL;
            model.isFeatured    = category.isFeatured;

            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Edit(EditCategoryViewModel model)
        {
            var existingCategory = CategoriesService.publicInstance.GetCategory(model.ID);
            existingCategory.Name           = model.Name;
            existingCategory.Description    = model.Description;
            existingCategory.ImageURL       = model.ImageURL;
            existingCategory.isFeatured     = model.isFeatured;
            CategoriesService.publicInstance.UpdateCategory(existingCategory);
            return RedirectToAction("CategoryTable");
        }
       
        [HttpPost]
        public ActionResult Delete(int ID)
        {
            CategoriesService.publicInstance.DeleteCategory(ID);
            return RedirectToAction("CategoryTable");
        }
    }
}

EcommerceWebsite/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EcommerceWebsite.Controllers
{
    public class SharedController : Controller
    {
        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            try
            {
                var file = Request.Files[0];
                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
                var path = Path.Combine(Server.MapPath("~/content/images"), fileName);
                file.SaveAs(path);
                result.Data = new { Success = true, ImageURL = string.Format("/content/images/{0}",fileName)};                
            }
            catch (Exception ex)
            {
                result.Data = new { Success = false, Message = ex.Message };
            }            
            return result;
        }
    }
}

EcommerceWebsite/Views/Category/CategoryTable.cshtml
@model EcommerceWebsite.Models.CategorySearchViewModel

<!--Some Scripts-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<div class="container">
    <hr />
    <form method="post" action="/Category/CategoryTable" class="form-horizontal">
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label for="Search">Search</label>
                    <input class="form-control"  placeholder="⌕Search.." id="searchTxt" name="Search" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>Action</label>
                    <div class="row">
                        <div class="col-md-4 pr-0">
                            <button class="btn btn-primary form-control" type="button" id="searchbtn">Search</button>
                        </div>
                        <div class="col-md-4 pr-0">
                            <button class="btn btn-primary form-control" type="button" id="resetbtn">Reset</button>
                        </div>
                        <div class="col-md-4 pr-0">
                            <button class="btn btn-primary form-control" type="button" id="newbtn">New</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div><!--Search Boxes and New Buttons-->

<br />
<div>
    <br />
    <h2>Category Table</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Category Name</th>
                <th>Products</th>
                <th class="wrap-td">Action</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Categories != null && Model.Categories.Count > 0)
            {
                foreach (var category in Model.Categories)
                {
                    <tr>
                        <td>@category.Name</td>
                        <td>@category.Products.Count</td>
                        <td>
                            @{  if (category.isFeatured == false)
                                { <text>Featured</text>}
                                else
                                { <text>-</text>}
                            }
                        </td>
                        <td>
                            <button class="editbtn" data-id="@category.ID">Edit</button>
                            <button class="deletebtn" data-id="@category.ID" data-toggle="modal" data-target="#exampleModal">Delete</button>
                        </td>
                    </tr>
                                    }
                                }
                                else
                                {
                                    <tr><td colspan="3" class="text-danger">No Category found.</td></tr>
                                }
        </tbody>
    </table>
</div><!-- Products Details and listing-->


<!-- Modal -->
<div class="modal hide" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete Changes</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure, you wanna delete the category?
            </div>
            <div class="modal-footer">
                <button type="button" id="yes-delete-btn" data-dismiss="modal" class="btn btn-primary">Yes,Delete</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script>
    $("#searchbtn").click(function () {
        var searchValue = $("#searchTxt").val();
        SearchFunction();
    });
    $("#resetbtn").click(function () {
        var searchValue = "";
        SearchFunction();
    });
    /*$("#searchTxt").keypress(function(event){
        var keycode = (event.keyCode ? event.keyCode : event.which);
        if(keycode == '13'){
            $("#searchbtn").focus();
        }
    });*/
    $("#newbtn").click(function () {
        $.ajax({
            url: '@Url.Action("Create","Category")'
        })
        .done(function (response) {
            $("#actionContainer").html(response)
            focusAction("actionContainer")
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert(XMLHttpRequest+" "+ textStatus+" "+ errorThrown);
        })
    });
    $(".editbtn").click(function () {
        $.ajax({
            url: '@Url.Action("Edit","Category")',/*'/Category/Edit',*/
            data:{
                    ID:$(this).attr('data-id')
                }
            })
            .done(function (response) {
                $("#actionContainer").html(response)
                focusAction("actionContainer");
                
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {

            });
    });
    $(".deletebtn").click(function () {

        $.ajax({
            type: 'POST',
            url: '@Url.Action("Delete","Category")',/*'/Category/Delete',*/
            data: {

                ID: $(".deletebtn").attr('data-id')
            }
        })
        .done(function (response) {
            $("#tableContainer").html(response)
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("Request Faliled");
        });
    });
    //Funtions
    function SearchFunction() {
        $.ajax({
            url: '@Url.Action("Category","CategoryTable")', /*'/Category/CategoryTable',*/
            data: {
                search: searchValue
            }
        })
            .done(function (response) {
                $("#tableContainer").html(response)
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {

            });
    }
    
</script>

EcommerceWebsite/Views/Category/Create.cshtml
@{
    ViewBag.Title = "Create";
    var imageURL = "/Content/images/system/placeholder-image.png";
    var trueChecked = Model.isFeatured ? "checked" : string.Empty;
    var falseChecked = !Model.isFeatured ? "checked" : string.Empty;
}

<h2>Create Category</h2>
<form role="form" id="createCategory" method="post">
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label for="Name">Name</label>
                <input name="Name" class="form-control" placeholder="Add Category Name" />
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="Description">Description</label>
                <input name="Description" class="form-control" placeholder="Enter ProductCategory Description" />
            </div>
            <div class="form-group">
                <label>Image</label>
                <input id="ImageURL" class="form-control" name="ImageURL" type="hidden" />
                <input id="imageUpload" class="form-control" name="Image" type="file" accept=".png, .jpg, .jpeg" />
            </div>
            <div class="form-group">
                <label for="isFeatured">Is Featured?</label>
                <div class="input-group">
                    <div class="radio form-control">
                        <label><input name="isFeatured" type="radio" value="True" @trueChecked /> True</label>
                    </div>
                    <div class="radio form-control">
                        <label><input name="isFeatured" type="radio" value="False" @falseChecked /> False</label>
                    </div>

                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="thumb">
                <img class="img-thumbnail img-fluid" id="categoryImage" src="@imageURL" />
            </div>
        </div>
    </div>

    <button id="saveBtn" type="button" class="btn btn-primary">Save</button>
    <button id="cancelBtn" type="button" class="btn btn-primary">Cancel</button>
</form>
<script>
    $("#imageUpload").change(function () {
        var element = this;
        var formData = new FormData();
        var totalFiles = element.files.length;
        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }
        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadImage","Shared")',/*'/Shared/UploadImage',*/
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
        })
        .done(function (response) {
            console.log(response);
            if (response.Success) {
                $("#ImageURL").val(response.ImageURL);
                $("#categoryImage").attr("src", response.ImageURL);
            }
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        });
    });
    $("#saveBtn").click(function () {
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Create", "Category")',/*'/Category/Create',*/
            data: $("#createCategory").serialize()
        })
        .done(function (response) {
            $("#tableContainer").html(response);
            $("#actionContainer").html("");
            focusAction("tableContainer");
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        });
    });
    $("#cancelBtn").click(function () {
        $("#actionContainer").html("");
        focusAction("tableContainer");
    });
</script>

EcommerceWebsite/Views/Category/Delete.cshtml
@model  DevClothing.Entities.Category
@{
    ViewBag.Title = "Delete";
}
<h2>Delete Category</h2>
<form method="post">
    <input type="hidden" value="@Model.ID" />
    <button type="submit">Delete</button>
    <a href="/Index">Cancel</a>
</form>

EcommerceWebsite/Views/Category/Edit.cshtml
@model EcommerceWebsite.Models.EditCategoryViewModel
@{
    ViewBag.Title = "Edit";

    var trueChecked = Model.isFeatured ? "checked" : string.Empty;
    var falseChecked = !Model.isFeatured ? "checked" : string.Empty;

    var imageURL = !string.IsNullOrEmpty(Model.ImageURL) ? Model.ImageURL : "/Content/images/system/placeholder-image.png";
}

<h2>Edit Category</h2>
<form id="editCategory">
    <input type="hidden" name="ID" value="@Model.ID"/>
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Name</label>
                <input class="form-control" name="Name" value="@Model.Name" />
            </div>
            <div class="form-group">
                <label>Description</label>
                <input class="form-control" name="Description" value="@Model.Description" />
            </div>
            <div class="form-group">
                <label>Image</label>
                <input type="hidden" id="ImageURL" name="ImageURL" value="@Model.ImageURL" />
                <input class="form-control" id="imageUpload" name="Image" type="file" accept=".png, .jpg, .jpeg" />
            </div>
            <div class="form-group">
                <label>Is Featured?</label>
                <div class="input-group">
                    <div class="radio form-control">
                        <label><input name="isFeatured" type="radio" value="True" @trueChecked /> True</label>
                    </div>
                    <div class="radio form-control">
                        <label><input name="isFeatured" type="radio" value="False" @falseChecked /> False</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="thumb">
                <img src="@imageURL" class="img-thumbnail img-fluid" id="categoryImage" />
            </div>
        </div>
    </div>
        <button id="updateBtn" type="button" class="btn btn-primary">Update</button>
        <button id="cancelBtn" type="button" class="btn btn-primary">Cancel</button>
</form>    
<script>
    $("#imageUpload").change(function () {
        var element = this;
        var totalFiles = element.files.length;
        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }
        $.ajax({
            type: 'POST',
            url: '/Shared/UploadImage',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
        })
        .done(function (response) {
            console.log(response);
            if (response.Success) {
                $("#ImageURL").val(response.ImageURL);
                $("#categoryImage").attr("src", response.ImageURL);
            }
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        });
    });
    $("#updateBtn").click(function () {
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Edit", "Category")',/*'/Category/Edit',*/
            data: $('#editCategory').serialize()
        })
            .done(function (response) {
                $("#tableContainer").html(response)
                $('#actionContainer').html("");
                focusAction("tableContainer");
            })
            .fail(function(XMLHttpRequest, textStatus, errorThrown){
                alert(textStatus = "Update request Failed",errorThrown)
            });
    });
    $("#cancelBtn").click(function () {
        $("#actionContainer").html("");
        focusAction("tableContainer");
    });
</script>

EcommerceWebsite/Views/Category/Index.cshtml
@{
    ViewBag.Title = "Categories";
}
<h2>Index</h2>
<section class="flat-row flat-iconbox">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-section">
                    <h2 class="title">
                        Categories
                    </h2>
                </div>
            </div>
        </div>
        <div id="tableContainer">
            @{Html.RenderAction("CategoryTable");
            }
        </div>
        <hr />
        <div id="actionContainer">

        </div>
    </div>
</section>
<script>
    function focusAction(divToFocus) {
        $('html, body').animate({
            scrollTop: $("#"+divToFocus).offset().top - 100
        }, 1000);
    }
</script>